#!/usr/bin/env bash

parentdir="$(dirname "$(pwd)")"


DRIVER_PATH="$parentdir/JQF/bin/jqf-afl-fuzz"

#/usr/bin/env bash -c "$parentdir/JQF/setup.sh"

EXEC_DIR="$(date +"%Y-%m-%d_%H-%M-%S")-afl"


classpath="$(pwd)/build/libs/growe_afl-1.0-SNAPSHOT-all.jar:$(pwd)/build/classes/groovy/main"
jqf_classpath="$($parentdir/JQF/scripts/examples_classpath.sh)"

seeds="$(pwd)/build/resources/main/seeds/"
dict="$(pwd)/build/resource/main/dictionaries/nextflow.dict"

mkdir -p "$EXEC_DIR" || return 1
cd "$EXEC_DIR" || return 1

memlimit=12288 #24576
timeouts=$((60*60 + 30))

/usr/bin/env bash -c "timeout ${timeouts}s $DRIVER_PATH -v -m $memlimit -c $classpath de.schemmea.ma.NfAFLTest testAFL -i $seeds -x $dict"

#remove nextflow generated shit
#rm -r work/
#rm -r .nextflow/
#rm .nextflow.log*
