#!/bin/bash

if [ $# -lt 2 ]; then
  echo "Usage: $0 ID-FROM ID-TO" 2>/dev/null
  exit 1
fi

id1=$1
id2=$2
time=$((3))
#time=$((1*60*60))
timeouts=$((time + 3))

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

for id in $(seq $id1 $id2); do

  echo "afl-$id timeout ${timeouts}s "
  screen -S "afl-$id" -dm -t "afl-$id"
  screen -S "afl-$id" -p "afl-$id" -X stuff "timeout ${timeouts}s $SCRIPT_DIR/run_afl $id ^M"

  sleep $timeouts

done
