<nextflow> ::= <shebang> <newline> <processes> <space> <workflow>

<shebang> ::= "#!/usr/bin/env nextflow"
<magicstring> ::= "382z9dfiusdpuzn5934magicstring9834n945zp9"
<processes> ::= <process> | <processes> <process>
<process> ::= <processheader> <curlyopen> <newline> <processbody> <newline> <curlyclose> <newline>
<processcall> ::= <identifier> <open> <close> <space>
<processcallpiped> ::= <processcall> <pipe> <processcall>
<processcalls> ::= <processcall> | <processcalls> <processcall> | <processcallpiped>
<processheader> ::= "process" <space> <identifier>
<processbody> ::=  <space> <input> <output> <script>
<input> ::= "input:" <newline> <inputvars> <newline>
<inputvars> ::= <inputvar> | <inputvars> <inputvar>
<inputvar> ::= <inputvartype> <space> <identifier> <newline>
<iotype> ::=  "val" | "path" | "each"  | "env" | "stdin" | "tuple"
<inputvartype> ::=  <iotype> | "each"
<output> ::= "output:" <newline> <outputvars> <newline>
<outputvars> ::= <outputvar> | <outputvars> <outputvar>
<outputvar> ::= <iotype> <space> <identifier> <newline>
<script> ::= "script:" <newline> <magicstring>
<workflow> ::= <workflowheader> <workflowbody>
<workflowheader> ::= "workflow" <space>
<workflowbody> ::= <curlyopen> <newline> <processcalls> <newline> <curlyclose>
<identifier> ::= <char> | <identifier> <char>
<char> ::= a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
<space> ::= " "
<curlyopen> ::= "{"
<curlyclose> ::= "}"
<open> ::= "("
<close> ::= ")"
<newline> ::= " \n "
<pipe> ::= " | "
<colon> ::= ":"
